### ISSUE TITLE
Thermometer can not send redstone signal?

### ISSUE THREAD

**Issue by ZHENGLOC** [halvors/Quantum#28] opened 2018-04-21 14:02 UTC
This may be a bug or my way is wrong.
https://i.imgur.com/Cp4tQkH.png

**Comment by ZHENGLOC** [comment] 2018-04-21 14:04
game version is 1.7.10

**Comment by halvors** [comment] 2018-04-22 04:03
@ZHENGLOC Thanks you so much for reporting! The issue is fixed and will be in the next release.

**Comment by ZHENGLOC** [comment] 2018-04-22 04:07
@halvors  Thank you! I think this mod is will be  better and better!

**Comment by halvors** [comment] 2018-04-22 23:16
@ZHENGLOC This is fixed in latest release.

**Closed as completed** 2018-04-22 23:54 UTC
Labels: Bug, 1.7.10, Fix commited, Fix released
