### ISSUE TITLE
Crash on local game entering

### ISSUE THREAD

**Issue by nictrace** [halvors/Quantum#37] opened 2018-05-08 09:34 UTC
#1.7.10
I think, static method here is not a good idea

`---- Minecraft Crash Report ----
// My bad.

Time: 08.05.18 12:17
Description: Ticking entity

java.lang.IncompatibleClassChangeError: Expecting non-static method org.halvors.nuclearphysics.common.event.handler.ItemEventHandler.onItemExpireEvent(Lnet/minecraftforge/event/entity/item/ItemExpireEvent;)V
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_114_ItemEventHandler_onItemExpireEvent_ItemExpireEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.entity.item.EntityItem.func_70071_h_(EntityItem.java:154)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at WorldServerOF.func_72870_g(WorldServerOF.java:347)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_114_ItemEventHandler_onItemExpireEvent_ItemExpireEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.entity.item.EntityItem.func_70071_h_(EntityItem.java:154)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at WorldServerOF.func_72870_g(WorldServerOF.java:347)

-- Entity being ticked --
Details:
	Entity Type: Item (net.minecraft.entity.item.EntityItem)
	Entity ID: 111
	Entity Name: item.item.egg
	Entity's Exact location: 23,13, 78,13, 268,79
	Entity's Block location: World: (23,78,268), Chunk: (at 7,4,12 in 1,16; contains blocks 16,0,256 to 31,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0,00, -0,00, 0,00
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: Q
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 625 Drop: 0
	Level seed: -2140901117562167464
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (60,64,252), Chunk: (at 12,4,12 in 3,15; contains blocks 48,0,240 to 63,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 44456 game time, 44456 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 2321 (now: false), thunder time: 109473 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_171, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 268450704 bytes (256 MB) / 577241088 bytes (550 MB) up to 954728448 bytes (910 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=ThisTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1024M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 13, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_E7 17 mods loaded, 17 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	CoFHCore{1.7.10R3.1.4} [CoFH Core] (CoFHCore-[1.7.10]3.1.4-329.jar) 
	UCHIJAAAA	DamageIndicatorsMod{3.2.3} [Damage Indicators] (DamageIndicatorsMod-3.2.3.jar) 
	UCHIJAAAA	IC2{2.2.823-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.823-experimental.jar) 
	UCHIJAAAA	ForgeMultipart{1.1.2.331} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
	UCHIJAAAA	Mekanism{9.1.0} [Mekanism] (Mekanism-1.7.10-9.1.0.281-client.jar) 
	UCHIJAAAA	nuclearphysics{0.1.36-dev} [Nuclear Physics] (nuclearphysics-1.7.10-0.1.36-dev.jar) 
	UCHIJAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJAAAA	WailaHarvestability{1.1.6} [Waila Harvestability] (WailaHarvestability-mc1.7.10-1.1.6.jar) 
	UCHIJAAAA	wawla{1.3.3} [What Are We Looking At] (Wawla_1.3.3_1.7.10.jar) 
	UCHIJAAAA	McMultipart{1.1.2.331} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
	UCHIJAAAA	ForgeMicroblock{1.1.2.331} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	CoFHCore: -[1.7.10]3.1.4-329
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'`

**Comment by halvors** [comment] 2018-05-08 13:42
@nictrace Yeah you mean in the event handler? Will fix this, it's a backport issue caused by 1.10+ using eventhandlers with the @EventBusSubscriber annotation.

**Comment by halvors** [comment] 2018-05-08 15:44
@nictrace If you'd like to contribute to this mod please let me know :) We need all the developers we can get, this really is just a community effort to bring back the old Atomic-Science mod! :)

**Comment by nictrace** [comment] 2018-05-08 19:55
Yes, I worked also for mod porting to 1.7.10, but your progress is great)
Currently I work on a Chemical Extractor for improving its compatibility to IC2, Thermal and Galacticraft

**Comment by halvors** [comment] 2018-05-08 20:03
@nictrace Nice, maybe you could join the discord server, easier to talk there :) https://discord.gg/DBRTKZT
Also, it's worth mentioning that if you're planning on contributing to this repository you should make your changes to the 1.10.2 branch. Then merge your changes when they're complete into 1.7.10 or 1.11.2 (and then 1.12.2).

This is so that we ensure that fixes and changes are in sync across all versions. Of course if there is 1.7.10 specific changes like rendering etc, you'll have to do that on the 1.7.10 branch. But never merge anything back into 1.10.2.

**Comment by halvors** [comment] 2018-05-09 16:03
Fixed in commit b06060c29d3872c01165dc6cb4d1479de7afad12

**Closed as completed** 2018-05-09 17:06 UTC
Labels: Bug, 1.7.10, Fix commited, Fix released
