### ISSUE TITLE
crash when open the game

### ISSUE THREAD

**Issue by ZHENGLOC** [halvors/Quantum#62] opened 2018-10-02 15:43 UTC
forge version：2765
mod version：0.1.38
https://paste.ubuntu.com/p/jkhbQh64Jd/

**Comment by Breadabix** [comment] 2018-10-02 22:23
Try removing optifine, it can cause issues with other mods

**Comment by halvors** [comment] 2018-10-04 00:07
Duplicate of #53

**Closed as completed by halvors** 2018-10-04 00:07 UTC
