### ISSUE TITLE
Game Crash when handling radioactive items with the hazmat suit

### ISSUE THREAD

**Issue by Kreassen** [halvors/Quantum#42] opened 2018-05-27 03:36 UTC
Everytime i pick up Yellowcake or Uranium, i get radioactive. But when i have the suit equiped the game keeps crashing. Wearing the suit on its own isnt a problem.

Edit: It doesnt matter what causes the radioation poisoning, crashes everytime i get in contact with radioation with the suit equiped

Edit 2: I tested it with the 3 Latest versions for 1.12.2 and still crashing, also tested without any other mods, still crashing :C 
[crash-2018-05-27_06.11.33-server.txt](https://github.com/halvors/Nuclear-Physics/files/2042262/crash-2018-05-27_06.11.33-server.txt)

**Comment by jdawg3636** [comment] 2018-05-27 22:34
[nuclear-physics-abstract-armor-crash.log](https://github.com/halvors/Nuclear-Physics/files/2043085/nuclear-physics-abstract-armor-crash.log)
I have the same issue; downgrading to 1.12.2-0.1.32 seems to fix.

**Comment by MeycsHD** [comment] 2018-05-28 13:36
I have the same issue...

**Comment by halvors** [comment] 2018-05-28 13:48
@Kreassen @jdawg3636 @MeycsHD Sorry for the inconvinience, will fix this as soon as possible. The issue is related to how mojang obfuscates the code. And is easy to fix.

**Comment by halvors** [comment] 2018-05-28 15:08
Fixed in commit 703093e5bc6bd572f7912b0dc08a4e35236ff8c2, will issue a new release soon.

**Comment by halvors** [comment] 2018-05-28 18:55
Fix released, grab the 0.1.37 version 👍

**Closed as completed by halvors** 2018-05-28 18:55 UTC
Labels: Bug, 1.12.2, Fix commited, Fix released

**Comment by Kreassen** [comment] 2018-05-29 13:33
Thanks man, is it normal that the nuclear reactor is so overpowered? the best energy cubes from mekanism are almost instantly full while reactors from extreme reactor take a while.
